spring.application.name=VaultAPI

# DATABASE
spring.datasource.url=jdbc:postgresql://ep-steep-sky-aiz29h4h-pooler.c-4.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_O8hDmQi1oafK

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=2005

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui

# JWT (temporary for now)
jwt.secret=DONT_TRY_TO_SEE_THIS_ON_MY_LAP_DEATH_NOTE
jwt.expiration=86400000